### ISSUE TITLE
Cannot read property 'startProblemCheck' of undefined

### ISSUE THREAD

**Issue by thischrisblack** [WebSpellChecker/wproofreader#24]
We are running webspellchecker via the Froala editor on Chrome.

With the cursor focused in the editor, hitting the ENTER key (i.e. creating a new line) results in this error in the console:

![image](https://user-images.githubusercontent.com/7775971/91471608-2a69f600-e84b-11ea-8123-24cbadc6c8c3.png)

Opening wscbundle.js in "Sources" shows this:

![image](https://user-images.githubusercontent.com/7775971/91471746-51c0c300-e84b-11ea-80c4-ea6d69954a35.png)

It seems that `this._sandbox` is undefined.

The functionality of the spellchecker seems fine, but the errors are an issue.

**Comment by jshaptala** [comment]
Hi @thischrisblack,

Our QA team tried to reproduce the issue you reported but with no luck.

However, we have an assumption that the issue might be caused by the conflict between the old SCAYT plugin for Froala and WProofreader.

Could you please check by `path/to/spell_checker.min.js` and see if it is loaded onto the page? If so, this is the old plugin that you need to remove.

This plugin contains the following piece of code which triggers the reported behavior:

```
// Reload markup on ENTER.
if (key_code == FE.KEYCODE.ENTER) {
    setTimeout(object.reloadMarkup, 0);
}
```

Looking forward to hearing from you.

Thanks,

**Comment by thischrisblack** [comment]
Yes, we have that script. We're loading it here, right after the Froala editor:
![image](https://user-images.githubusercontent.com/7775971/91850304-527e9e00-ec2b-11ea-8fec-f3de474057bd.png)

What shall I replace it with? And thanks!

**Comment by jshaptala** [comment]
You need to remove that script and use the correct initialization of spelling/grammar checking components as described [here](https://docs.webspellchecker.net/display/WebSpellCheckerCloud/Initializing+WProofreader+in+Froala+Editor).

**Comment by thischrisblack** [comment]
Thanks! That works.

**Comment by jshaptala** [comment]
We are glad to help! Thanks for confirming that it works.
