### ISSUE TITLE
click on "source" button disabled the plugin. 

### ISSUE THREAD

**Issue by Gu3** [WebSpellChecker/wproofreader#25]
Hi ! 
On CkEditor 4, when we click on the source button, the plugin becomes disabled : 

Origin :
![image](https://user-images.githubusercontent.com/5227741/101139578-0704d300-3612-11eb-8012-af0ce613c845.png)

OnClick Situation : 
![image](https://user-images.githubusercontent.com/5227741/101139651-26036500-3612-11eb-9e82-627c6cec6693.png)

Back to main screen:
![image](https://user-images.githubusercontent.com/5227741/101139727-3c112580-3612-11eb-81a3-01cc0b62f312.png)

Thanks you :)

**Comment by jshaptala** [comment]
Hi @Gu3,

I've transferred your request to a different repo which is related to WProofreader. 

This is expected behavior when WProofreader is disabled in the source mode of CKEditor 4.  It was done intentionally in order not to populate the view with underlines of HTML tags or CSS classes. 

Check the original request here: [WProofreader is active in source mode highlighting HTML tags [CKEditor 4] #1](https://github.com/WebSpellChecker/wproofreader/issues/1)

You may re-enable it manually by passing an empty array `disableAutoSearchIn: []`.

```
<script>
    window.WEBSPELLCHECKER_CONFIG = {
        ....
        disableAutoSearchIn: []
        ....
    };
</script>
```
